language: node_js
node_js:
  - "node"
  - "9"
  - "6"
  - "4"

cache:
  npm: true
  directories:
    - node_modules

sudo: false

os:
  - linux
  - osx

matrix:
  fast_finish: true

before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
  - yarn global add greenkeeper-lockfile@1
install: npm install && yarn
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
